// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzRbVVZuJnHhtzCzhmcKn22n9wWWKgoKE',
    appId: '1:776332381264:web:24ed4f979aab6fead8d555',
    messagingSenderId: '776332381264',
    projectId: 'flutterfire-57d9b',
    authDomain: 'flutterfire-57d9b.firebaseapp.com',
    storageBucket: 'flutterfire-57d9b.firebasestorage.app',
    measurementId: 'G-3FLT72W5HK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7ICJfE-dhCfjOBel7ZSdp8bqT_7W8FeM',
    appId: '1:776332381264:android:c288e01cb8f712a9d8d555',
    messagingSenderId: '776332381264',
    projectId: 'flutterfire-57d9b',
    storageBucket: 'flutterfire-57d9b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgN8Brflc44ENME4j9Z_gmDpuQJ5paZUg',
    appId: '1:776332381264:ios:48e0a5be6ef4b3c4d8d555',
    messagingSenderId: '776332381264',
    projectId: 'flutterfire-57d9b',
    storageBucket: 'flutterfire-57d9b.firebasestorage.app',
    androidClientId: '776332381264-6826qo6clcnf6ej8730f551jok6om8gs.apps.googleusercontent.com',
    iosClientId: '776332381264-mnf69fquict516to1aj9fg1a844a4sk8.apps.googleusercontent.com',
    iosBundleId: 'com.example.exam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgN8Brflc44ENME4j9Z_gmDpuQJ5paZUg',
    appId: '1:776332381264:ios:48e0a5be6ef4b3c4d8d555',
    messagingSenderId: '776332381264',
    projectId: 'flutterfire-57d9b',
    storageBucket: 'flutterfire-57d9b.firebasestorage.app',
    androidClientId: '776332381264-6826qo6clcnf6ej8730f551jok6om8gs.apps.googleusercontent.com',
    iosClientId: '776332381264-mnf69fquict516to1aj9fg1a844a4sk8.apps.googleusercontent.com',
    iosBundleId: 'com.example.exam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmhexen8_nqGf1j5QeA67xTVT1IBd39b4',
    appId: '1:776332381264:web:311cbbe43a9836a7d8d555',
    messagingSenderId: '776332381264',
    projectId: 'flutterfire-57d9b',
    authDomain: 'flutterfire-57d9b.firebaseapp.com',
    storageBucket: 'flutterfire-57d9b.firebasestorage.app',
    measurementId: 'G-TR151N2L3L',
  );
}
