import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static final Map<String, Map<String, String>> _localizedValues = {
    // ================= ARABIC =================
    'ar': {
      'app_title': 'منصة الاختبارات الذكية',
      'app_subtitle': 'اختبارات متطورة مدعومة بالذكاء الاصطناعي',
      'welcome_title': 'مرحباً بك',
      'welcome_sub': 'سجّل الدخول لحفظ تقدمك ومزامنة نتائجك\nأو تابع كضيف',
      'google_login': 'تسجيل الدخول باستخدام Google',
      'guest_login': 'المتابعة كضيف',
      'connecting_google': 'جاري الاتصال بحساب Google...',
      'saving_account': 'جاري حفظ بيانات الحساب ومزامنة النتائج...',
      'login_cancelled': 'تم إلغاء تسجيل الدخول',
      'login_failed': 'تعذر تسجيل الدخول، يرجى المحاولة لاحقاً',
      'app_welcome_user': 'أهلاً بك',
      'guest_user': 'زائر التطبيق',
      'guest_email': 'مستخدم ضيف',
      'guest_notice': 'هذه الإحصائيات محفوظة محليًا على الجهاز\nسجّل الدخول لحفظها على حسابك',
      'correct_answers': 'إجابات صحيحة',
      'wrong_answers': 'إجابات خاطئة',
      'must_login_review': 'يجب تسجيل الدخول لمراجعة الإجابات',
      'must_login_reports': 'يجب تسجيل الدخول لتظهر التقارير',
      'admin_dashboard': 'لوحة تحكم المسؤول',
      'leaderboard': 'لوحة المتصدرين',
      'last_cognitive_report': 'آخر تقرير معرفي',
      'full_cognitive_report': 'التقرير المعرفي الشامل',
      'logout': 'تسجيل الخروج',
      'logout_confirm_title': 'تسجيل خروج',
      'logout_confirm_msg': 'هل أنت متأكد من تسجيل الخروج؟',
      'cancel': 'إلغاء',
      'yes': 'نعم',
      'ok': 'موافق',
      'save': 'حفظ',
      'update': 'تحديث',
      'change_image': 'تغيير الصورة',
      'enter_custom_language': 'أدخل اسم اللغة (مثال: Swahili)',
      'categories': 'الأقسام والاشتراكات',
      'select_category': 'اختر الفئة',
      'search_category': 'ابحث عن قسم...',
      'add_category': 'إضافة فئة جديدة',
      'edit_category': 'تعديل الفئة',
      'delete_category': 'حذف',
      'category_title': 'عنوان الفئة',
      'category_prompt': 'نوع الاسئلة (الوصف أو المواضيع)',
      'target_language': 'لغة الأسئلة المحددة',
      'select_image': 'اختر صورة للفئة',
      'delete_category_confirm': 'هل أنت متأكد من حذف هذه الفئة؟',
      'select_difficulty': 'اختر مستوى الصعوبة',
      'choose_difficulty': 'اختر مستوى الصعوبة',
      'exam_language': 'لغة الاختبار',
      'easy': 'سهل',
      'medium': 'متوسط',
      'hard': 'صعب',
      'extreme': 'صعب جداً',
      'start_quiz': 'ابدأ الاختبار',
      'no_categories': 'لا توجد أقسام متاحة حالياً',
      'question': 'سؤال',
      'question_detail': 'تفاصيل السؤال',
      'confirm_answer': 'تأكيد الإجابة',
      'submit': 'إنهاء الاختبار',
      'next': 'التالي',
      'previous': 'السابق',
      'score': 'النتيجة النهائيّة',
      'your_score': 'درجتك الحالية',
      'quiz_completed': 'تهانينا! أكملت الاختبار',
      'review_answers': 'مراجعة الإجابات',
      'back_home': 'العودة للرئيسية',
      'back_to_categories': 'العودة إلى الفئات',
      'view_cognitive_report': 'عرض التقرير المعرفي',
      'correct': 'صحيحة',
      'wrong': 'خاطئة',
      'excellent_result': 'نتيجة ممتازة! 🎉',
      'great_performance': 'أداء ممتاز! 👏',
      'good_performance': 'أداء جيد 🙂',
      'try_again': 'حاول مرة أخرى 💡',
      'score_sub_80': 'أحسنت! لديك معرفة جيدة جداً بالمعلومات.',
      'score_sub_50': 'نتيجة طيبة، مع بعض المراجعة ستصبح أفضل!',
      'score_sub_low': 'لا تقلق، تكرار الاختبار يساعدك على التعلم والتحسن بسرعة.',
      'press_again_exit': 'اضغط مرة أخرى للخروج',
      'review_correct': 'مراجعة الأسئلة المجابة بصحة',
      'review_wrong': 'مراجعة الأسئلة الخاطئة',
      'offline_mode': 'وضع بدون إنترنت',
      'offline_no_quiz': 'لا يوجد اتصال بالإنترنت\nولا يوجد اختبار محفوظ لهذا المجال',
      'offline_used_cache': 'تم استخدام أسئلة محفوظة سابقاً (وضع بدون إنترنت)',
      'new_quiz_generated': 'تم إنشاء أسئلة جديدة بنجاح',
      'cached_loaded_server_busy': 'تم تحميل الأسئلة من الأرشيف المحفوظ',
      'server_error': 'تعذر توليد الأسئلة، يرجى التأكد من الإنترنت والمحاولة لاحقاً',
      'language': 'اللغة',
      'change_language': 'تغيير لغة التطبيق',
      'arabic': 'العربية',
      'english': 'English',
      'spanish': 'Español',
      'skip': 'تخطي',
      'get_started': 'ابدأ الآن',
      'onboarding_title_1': 'اختبارات ذكية مخصصة',
      'onboarding_desc_1': 'يقوم الذكاء الاصطناعي بتوليد أسئلة متجددة وفريدة في كل مرة تختبر فيها نفسك.',
      'onboarding_title_2': 'تحليل معرفي شامل',
      'onboarding_desc_2': 'احصل على تقارير تفصيلية تحلل نقاط قوتك ومجالات التحسين بذكاء.',
      'onboarding_title_3': 'مزامنة وتنافس',
      'onboarding_desc_3': 'حافِظ على سجل إنجازاتك وتنافس في لوحة المتصدرين عالمياً.',
      'no_reports_yet': 'لا توجد تقارير محفوظة بعد\nقم بحل بعض الاختبارات أولاً لاستخراج التقرير الشامل',
      'reports_history': 'سجل التقارير المعرفية',
      'global_cognitive_report': 'التقرير المعرفي التراكمي الشامل',
      'accuracy_rate': 'معدل الدقة المعرفية',
      'total_time': 'الوقت الإجمالي المستغرق',
      'total_questions_answered': 'إجمالي الأسئلة المجاوبة',
      'permission_photo_title': 'إذن الوصول للصور',
      'permission_photo_msg': 'لاختيار صورة للفئة، يجب السماح للتطبيق بالوصول إلى معرض الصور. يرجى قبول الإذن من الإعدادات.',
      'open_settings': 'فتح الإعدادات',
      'required_field': 'الحقل مطلوب',
      'tutorial_add_category': 'أضغط هنا لأضافة فئة جديدة',
      'tutorial_edit_category': 'اضغط مطولًا لتعديل هذه الفئة',
      'delete_user_title': 'حذف حساب مستخدم نهائياً',
      'delete_user_confirm': 'هل أنت متأكد من حذف هذا الحساب وجميع إحصائياته نهائياً؟',
      'delete_user_success': 'تم حذف حساب المستخدم وجميع بياناته نهائياً',
      'delete_user_error': 'حدث خطأ أثناء الحذف',
      'delete_permanently': 'حذف نهائي',
      'analytics_and_stats': 'التحليلات والإحصائيات',
      'user_management': 'إدارة المستخدمين',
      'total_users': 'المستخدمين',
      'total_questions': 'إجمالي الأسئلة',
      'accuracy_indicator': 'مؤشر الدقة العام للتطبيق',
      'user_accuracy': 'دقة المستخدمين',
      'top_performing_users': 'أفضل المستخدمين أداءً',
      'no_users_found': 'لا توجد بيانات مستخدمين بعد',
      'filter_users': 'تصفية المستخدمين:',
      'all_users': 'الكل',
      'active_users_only': 'الفعالين فقط',
      'no_matching_users': 'لم يتم العثور على مستخدمين مطبقين للشروط',
      'search_user_hint': 'بحث باسم المستخدم أو البريد...',
      'latest_analysis_title': 'تحليل آخر اختبار',
      'general_summary': 'الملخص العام',
      'success_rate': 'نسبة النجاح',
      'performance_trend': 'اتجاه الأداء',
      'cumulative_accuracy_curve': 'منحنى الدقة التراكمي أثناء الاختبار',
      'cumulative_curve_desc': 'يُظهر تطور نسبة الدقة التراكمية مع تقدم الأسئلة (0% إلى 100%)',
      'weakness_by_category': 'تحليل الضعف حسب الفئة',
      'errors_suffix': 'أخطاء',
      'comprehensive_smart_analysis': 'التحليل الذكي الشامل',
      'overall_summary_all_quizzes': 'الملخص العام لكل الاختبارات',
      'overall_accuracy': 'الدقة العامة',
      'overall_accuracy_indicator': 'مؤشر الدقة العام',
      'overall_performance_trend': 'الاتجاه العام للأداء',
      'cumulative_performance_curve': 'منحنى الأداء التراكمي الشامل',
      'cumulative_curve_desc_all': 'تطور نسبة الدقة التراكمية عبر كافة الأسئلة والاختبارات (0% إلى 100%)',
      'category_weakness_cumulative': 'الضعف حسب الفئات (تراكمي)',
      'trend_excellent': 'أداء ممتاز ومستقر عبر جميع الاختبارات',
      'trend_good': 'أداء جيد مع وجود تذبذب في بعض الجلسات',
      'trend_weak': 'يظهر ضعف عام في الأداء عبر معظم الاختبارات',
      'analyzed_quizzes_prefix': 'تم تحليل',
      'quizzes_suffix': 'اختبار.',
      'accuracy_rate_prefix': 'نسبة الدقة العامة',
    },

    // ================= ENGLISH =================
    'en': {
      'app_title': 'Smart Exam Platform',
      'app_subtitle': 'Advanced AI-Powered Testing Platform',
      'welcome_title': 'Welcome',
      'welcome_sub': 'Sign in to save your progress and sync results\nor continue as guest',
      'google_login': 'Sign in with Google',
      'guest_login': 'Continue as Guest',
      'connecting_google': 'Connecting to Google Account...',
      'saving_account': 'Saving account data and syncing...',
      'login_cancelled': 'Sign in cancelled',
      'login_failed': 'Sign in failed, please try again later',
      'app_welcome_user': 'Welcome',
      'guest_user': 'Guest User',
      'guest_email': 'Guest Account',
      'guest_notice': 'These stats are saved locally on your device.\nSign in to sync with your account.',
      'correct_answers': 'Correct Answers',
      'wrong_answers': 'Wrong Answers',
      'must_login_review': 'You must sign in to review answers',
      'must_login_reports': 'You must sign in to view cognitive reports',
      'admin_dashboard': 'Admin Dashboard',
      'leaderboard': 'Leaderboard',
      'last_cognitive_report': 'Latest Cognitive Report',
      'full_cognitive_report': 'Comprehensive Cognitive Report',
      'logout': 'Sign Out',
      'logout_confirm_title': 'Sign Out',
      'logout_confirm_msg': 'Are you sure you want to sign out?',
      'cancel': 'Cancel',
      'yes': 'Yes',
      'ok': 'OK',
      'save': 'Save',
      'update': 'Update',
      'change_image': 'Change Image',
      'enter_custom_language': 'Enter language name (e.g., Swahili)',
      'categories': 'Categories & Topics',
      'select_category': 'Select Category',
      'search_category': 'Search categories...',
      'add_category': 'Add New Category',
      'edit_category': 'Edit Category',
      'delete_category': 'Delete',
      'category_title': 'Category Title',
      'category_prompt': 'Questions Scope (Description / Topics)',
      'target_language': 'Target Questions Language',
      'select_image': 'Select Category Image',
      'delete_category_confirm': 'Are you sure you want to delete this category?',
      'select_difficulty': 'Select Difficulty Level',
      'choose_difficulty': 'Choose Difficulty',
      'exam_language': 'Exam Language',
      'easy': 'Easy',
      'medium': 'Medium',
      'hard': 'Hard',
      'extreme': 'Very Hard',
      'start_quiz': 'Start Quiz',
      'no_categories': 'No categories available currently',
      'question': 'Question',
      'question_detail': 'Question Detail',
      'confirm_answer': 'Confirm Answer',
      'submit': 'Submit Quiz',
      'next': 'Next',
      'previous': 'Previous',
      'score': 'Final Score',
      'your_score': 'Your Current Score',
      'quiz_completed': 'Congratulations! Quiz Completed',
      'review_answers': 'Review Answers',
      'back_home': 'Back to Home',
      'back_to_categories': 'Back to Categories',
      'view_cognitive_report': 'View Cognitive Report',
      'correct': 'Correct',
      'wrong': 'Wrong',
      'excellent_result': 'Excellent Result! 🎉',
      'great_performance': 'Great Performance! 👏',
      'good_performance': 'Good Performance 🙂',
      'try_again': 'Try Again 💡',
      'score_sub_80': 'Well done! You have a great understanding of the material.',
      'score_sub_50': 'Good score! With a little review, you will improve even more.',
      'score_sub_low': 'Don\'t worry, repeating the test helps you learn and improve quickly.',
      'press_again_exit': 'Press back again to exit',
      'review_correct': 'Review Correct Questions',
      'review_wrong': 'Review Incorrect Questions',
      'offline_mode': 'Offline Mode',
      'offline_no_quiz': 'No internet connection\nand no saved quiz for this topic',
      'offline_used_cache': 'Used previously cached questions (Offline Mode)',
      'new_quiz_generated': 'New questions generated successfully',
      'cached_loaded_server_busy': 'Loaded questions from saved archive',
      'server_error': 'Failed to generate questions, check connection and try again',
      'language': 'Language',
      'change_language': 'Change App Language',
      'arabic': 'العربية',
      'english': 'English',
      'spanish': 'Español',
      'skip': 'Skip',
      'get_started': 'Get Started',
      'onboarding_title_1': 'Smart Personalised Quizzes',
      'onboarding_desc_1': 'AI generates unique and fresh questions every single time you take a test.',
      'onboarding_title_2': 'Comprehensive Analysis',
      'onboarding_desc_2': 'Receive detailed cognitive reports analysing your strengths and areas for growth.',
      'onboarding_title_3': 'Sync & Compete',
      'onboarding_desc_3': 'Save your achievements and compete on the global leaderboard.',
      'no_reports_yet': 'No saved cognitive reports yet\nTake a few quizzes first to generate a full report',
      'reports_history': 'Cognitive Reports History',
      'global_cognitive_report': 'Comprehensive Cognitive Report',
      'accuracy_rate': 'Cognitive Accuracy Rate',
      'total_time': 'Total Time Spent',
      'total_questions_answered': 'Total Questions Answered',
      'permission_photo_title': 'Photo Gallery Permission',
      'permission_photo_msg': 'To select a category image, please grant photo gallery permission in settings.',
      'open_settings': 'Open Settings',
      'required_field': 'Field is required',
      'tutorial_add_category': 'Tap here to add a new category',
      'tutorial_edit_category': 'Long press to edit this category',
      'delete_user_title': 'Delete User Account Permanently',
      'delete_user_confirm': 'Are you sure you want to delete this account and all its stats permanently?',
      'delete_user_success': 'User account and all data deleted permanently',
      'delete_user_error': 'An error occurred during deletion',
      'delete_permanently': 'Delete Permanently',
      'analytics_and_stats': 'Analytics & Statistics',
      'user_management': 'User Management',
      'total_users': 'Users',
      'total_questions': 'Total Questions',
      'accuracy_indicator': 'Overall Application Accuracy Indicator',
      'user_accuracy': 'User Accuracy',
      'top_performing_users': 'Top Performing Users',
      'no_users_found': 'No user data available yet',
      'filter_users': 'Filter Users:',
      'all_users': 'All',
      'active_users_only': 'Active Only',
      'no_matching_users': 'No users matched the criteria',
      'search_user_hint': 'Search by username or email...',
      'latest_analysis_title': 'Latest Quiz Analysis',
      'general_summary': 'General Overview',
      'success_rate': 'Success Rate',
      'performance_trend': 'Performance Trend',
      'cumulative_accuracy_curve': 'Cumulative Accuracy Curve',
      'cumulative_curve_desc': 'Shows cumulative accuracy progression as questions advance (0% to 100%)',
      'weakness_by_category': 'Category Weakness Analysis',
      'errors_suffix': 'errors',
      'comprehensive_smart_analysis': 'Comprehensive Smart Analysis',
      'overall_summary_all_quizzes': 'Overall Summary Across All Quizzes',
      'overall_accuracy': 'Overall Accuracy',
      'overall_accuracy_indicator': 'Overall Accuracy Indicator',
      'overall_performance_trend': 'Overall Performance Trend',
      'cumulative_performance_curve': 'Overall Cumulative Performance Curve',
      'cumulative_curve_desc_all': 'Cumulative accuracy progression across all questions and quizzes (0% to 100%)',
      'category_weakness_cumulative': 'Category Weakness (Cumulative)',
      'trend_excellent': 'Excellent and stable performance across all quizzes',
      'trend_good': 'Good performance with slight variation across some sessions',
      'trend_weak': 'Shows general performance weakness across most quizzes',
      'analyzed_quizzes_prefix': 'Analyzed',
      'quizzes_suffix': 'quizzes.',
      'accuracy_rate_prefix': 'Overall accuracy rate',
    },

    // ================= SPANISH =================
    'es': {
      'app_title': 'Plataforma de Exámenes Inteligente',
      'app_subtitle': 'Plataforma de pruebas avanzada impulsada por IA',
      'welcome_title': 'Bienvenido',
      'welcome_sub': 'Inicia sesión para guardar tu progreso y sincronizar resultados\no continúa como invitado',
      'google_login': 'Iniciar sesión con Google',
      'guest_login': 'Continuar como invitado',
      'connecting_google': 'Conectando con la cuenta de Google...',
      'saving_account': 'Guardando datos de cuenta y sincronizando...',
      'login_cancelled': 'Inicio de sesión cancelado',
      'login_failed': 'Error al iniciar sesión, inténtalo más tarde',
      'app_welcome_user': 'Bienvenido',
      'guest_user': 'Usuario invitado',
      'guest_email': 'Cuenta de invitado',
      'guest_notice': 'Estas estadísticas se guardan localmente en tu dispositivo.\nInicia sesión para sincronizar con tu cuenta.',
      'correct_answers': 'Respuestas Correctas',
      'wrong_answers': 'Respuestas Incorrectas',
      'must_login_review': 'Debes iniciar sesión para revisar respuestas',
      'must_login_reports': 'Debes iniciar sesión para ver informes cognitivos',
      'admin_dashboard': 'Panel de Administración',
      'leaderboard': 'Tabla de Clasificación',
      'last_cognitive_report': 'Último Informe Cognitivo',
      'full_cognitive_report': 'Informe Cognitivo Integral',
      'logout': 'Cerrar Sesión',
      'logout_confirm_title': 'Cerrar Sesión',
      'logout_confirm_msg': '¿Estás seguro de que deseas cerrar sesión?',
      'cancel': 'Cancelar',
      'yes': 'Sí',
      'ok': 'Aceptar',
      'save': 'Guardar',
      'update': 'Actualizar',
      'change_image': 'Cambiar Imagen',
      'enter_custom_language': 'Introduce el nombre del idioma (ej. Swahili)',
      'categories': 'Categorías y Temas',
      'select_category': 'Seleccionar Categoría',
      'search_category': 'Buscar categorías...',
      'add_category': 'Añadir Nueva Categoría',
      'edit_category': 'Editar Categoría',
      'delete_category': 'Eliminar',
      'category_title': 'Título de Categoría',
      'category_prompt': 'Ámbito del Tema (Descripción / Temas)',
      'target_language': 'Idioma Objetivo de Preguntas',
      'select_image': 'Seleccionar Imagen de Categoría',
      'delete_category_confirm': '¿Estás seguro de que deseas eliminar esta categoría?',
      'select_difficulty': 'Seleccionar Nivel de Dificultad',
      'choose_difficulty': 'Elegir Dificultad',
      'exam_language': 'Idioma del Examen',
      'easy': 'Fácil',
      'medium': 'Medio',
      'hard': 'Difícil',
      'extreme': 'Muy Difícil',
      'start_quiz': 'Iniciar Examen',
      'no_categories': 'No hay categorías disponibles actualmente',
      'question': 'Pregunta',
      'question_detail': 'Detalle de Pregunta',
      'confirm_answer': 'Confirmar Respuesta',
      'submit': 'Enviar Examen',
      'next': 'Siguiente',
      'previous': 'Anterior',
      'score': 'Puntuación Final',
      'your_score': 'Tu Puntuación Actual',
      'quiz_completed': '¡Felicidades! Examen completado',
      'review_answers': 'Revisar Respuestas',
      'back_home': 'Volver al Inicio',
      'back_to_categories': 'Volver a Categorías',
      'view_cognitive_report': 'Ver Informe Cognitivo',
      'correct': 'Correctas',
      'wrong': 'Incorrectas',
      'excellent_result': '¡Resultado Excelente! 🎉',
      'great_performance': '¡Excelente Rendimiento! 👏',
      'good_performance': 'Buen Rendimiento 🙂',
      'try_again': 'Inténtalo de nuevo 💡',
      'score_sub_80': '¡Bien hecho! Tienes un gran conocimiento de la materia.',
      'score_sub_50': '¡Buen resultado! Con un poco de repaso mejorarás aún más.',
      'score_sub_low': 'No te preocupes, repetir la prueba te ayuda a aprender y mejorar rápidamente.',
      'press_again_exit': 'Presiona de nuevo para salir',
      'review_correct': 'Revisar Preguntas Correctas',
      'review_wrong': 'Revisar Preguntas Incorrectas',
      'offline_mode': 'Modo Sin Conexión',
      'offline_no_quiz': 'Sin conexión a Internet\ny sin examen guardado para este tema',
      'offline_used_cache': 'Preguntas guardadas usadas previamente (Modo Sin Conexión)',
      'new_quiz_generated': 'Nuevas preguntas generadas con éxito',
      'cached_loaded_server_busy': 'Preguntas cargadas desde el archivo guardado',
      'server_error': 'Error al generar preguntas, comprueba tu conexión e inténtalo de nuevo',
      'language': 'Idioma',
      'change_language': 'Cambiar Idioma de la Aplicación',
      'arabic': 'العربية',
      'english': 'English',
      'spanish': 'Español',
      'skip': 'Omitir',
      'get_started': 'Comenzar Ahora',
      'onboarding_title_1': 'Exámenes Inteligentes Personalizados',
      'onboarding_desc_1': 'La IA genera preguntas únicas y frescas cada vez que realizas una prueba.',
      'onboarding_title_2': 'Análisis Cognitivo Integral',
      'onboarding_desc_2': 'Recibe informes detallados que analizan tus fortalezas y áreas de mejora.',
      'onboarding_title_3': 'Sincroniza y Compite',
      'onboarding_desc_3': 'Guarda tus logros y compite en la tabla de clasificación mundial.',
      'no_reports_yet': 'No hay informes cognitivos guardados aún\nRealiza algunos exámenes para obtener un informe completo',
      'reports_history': 'Historial de Informes Cognitivos',
      'global_cognitive_report': 'Informe Cognitivo Integral',
      'accuracy_rate': 'Tasa de Precisión Cognitiva',
      'total_time': 'Tiempo Total Empleado',
      'total_questions_answered': 'Total de Preguntas Respondidas',
      'permission_photo_title': 'Permiso de Galería de Fotos',
      'permission_photo_msg': 'Para seleccionar una imagen de categoría, concede permiso de galería en los ajustes.',
      'open_settings': 'Abrir Ajustes',
      'required_field': 'Campo requerido',
      'tutorial_add_category': 'Toca aquí para añadir una nueva categoría',
      'tutorial_edit_category': 'Mantén presionado para editar esta categoría',
      'delete_user_title': 'Eliminar Cuenta de Usuario Definitivamente',
      'delete_user_confirm': '¿Estás seguro de que deseas eliminar esta cuenta y todas sus estadísticas?',
      'delete_user_success': 'Cuenta de usuario y datos eliminados definitivamente',
      'delete_user_error': 'Ocurrió un error al eliminar',
      'delete_permanently': 'Eliminar Definitivamente',
      'analytics_and_stats': 'Análisis y Estadísticas',
      'user_management': 'Gestión de Usuarios',
      'total_users': 'Usuarios',
      'total_questions': 'Total de Preguntas',
      'accuracy_indicator': 'Indicador General de Precisión de la Aplicación',
      'user_accuracy': 'Precisión de Usuarios',
      'top_performing_users': 'Usuarios con Mejor Rendimiento',
      'no_users_found': 'Aún no hay datos de usuarios disponibles',
      'filter_users': 'Filtrar Usuarios:',
      'all_users': 'Todos',
      'active_users_only': 'Solo Activos',
      'no_matching_users': 'No se encontraron usuarios que coincidan con los criterios',
      'search_user_hint': 'Buscar por nombre de usuario o correo...',
      'latest_analysis_title': 'Análisis del Último Examen',
      'general_summary': 'Resumen General',
      'success_rate': 'Tasa de Éxito',
      'performance_trend': 'Tendencia de Rendimiento',
      'cumulative_accuracy_curve': 'Curva de Precisión Acumulada',
      'cumulative_curve_desc': 'Muestra la progresión de la precisión acumulada a medida que avanzan las preguntas (0% a 100%)',
      'weakness_by_category': 'Análisis de Debilidades por Categoría',
      'errors_suffix': 'errores',
      'comprehensive_smart_analysis': 'Análisis Inteligente Integral',
      'overall_summary_all_quizzes': 'Resumen General de Todos los Exámenes',
      'overall_accuracy': 'Precisión General',
      'overall_accuracy_indicator': 'Indicador de Precisión General',
      'overall_performance_trend': 'Tendencia General de Rendimiento',
      'cumulative_performance_curve': 'Curva de Rendimiento Acumulado General',
      'cumulative_curve_desc_all': 'Progresión de precisión acumulada en todas las preguntas y exámenes (0% a 100%)',
      'category_weakness_cumulative': 'Debilidad por Categorías (Acumulada)',
      'trend_excellent': 'Rendimiento excelente y estable en todas las pruebas',
      'trend_good': 'Buen rendimiento con ligera variación en algunas sesiones',
      'trend_weak': 'Muestra debilidad general de rendimiento en la mayoría de las pruebas',
      'analyzed_quizzes_prefix': 'Analizados',
      'quizzes_suffix': 'exámenes.',
      'accuracy_rate_prefix': 'Tasa de precisión general',
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['ar', 'en', 'es'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

extension LocalizationExtension on BuildContext {
  String tr(String key) {
    return AppLocalizations.of(this)?.translate(key) ?? key;
  }
}
